import {test} from 'node:test';
import assert from 'node:assert/strict';
import {position,number,type Trade} from '../src/calculation.ts';
const t=(type:'BUY'|'SELL',price:string,quantity:string,fee='0',n=1):Trade=>({transaction_id:String(n),type,price,quantity,fee,trade_date:`2026-10-${String(n).padStart(2,'0')}`,created_at:`2026-10-${String(n).padStart(2,'0')}T00:00:00.000Z`});
test('요청한 NVDA 시나리오: 185 평단 / 8.11% / 부분매도',()=>{const buys=[t('BUY','180','5'),t('BUY','190','5','0',2)];let p=position(buys,'200');assert.equal(p.quantity,'10');assert.equal(p.average,'185');assert.equal(p.cost,'1850');assert.equal(p.value,'2000');assert.equal(p.pnl,'150');assert.equal(Number(p.rate).toFixed(2),'8.11');p=position([...buys,t('SELL','210','3','0',3)],'200');assert.equal(p.quantity,'7');assert.equal(p.average,'185');assert.equal(p.realized,'75');assert.equal(p.pnl,'105');assert.equal(Number(p.realizedRate).toFixed(2),'13.51')});
test('수수료 원가 / 매도 후 추가매수 / 전량 매도',()=>{const ts=[t('BUY','100','10','10'),t('SELL','120','4','2',2)];const p=position(ts,'120');assert.equal(p.average,'100');assert.equal(p.averageCost,'101');assert.equal(p.realized,'74');assert.equal(p.cost,'606');const next=position([...ts,t('BUY','200','6','6',3)],'150');assert.equal(next.average,'150');assert.equal(next.averageCost,'151');assert.equal(next.cost,'1812');const closed=position([...ts,t('SELL','110','6','1',3)]);assert.equal(closed.quantity,'0');assert.equal(closed.cost,'0');assert.equal(closed.realized,'127')});
test('초과매도, 과거매수 삭제 및 수정 차단',()=>{assert.throws(()=>position([t('BUY','100','2'),t('SELL','110','3','0',2)]),/초과/);assert.throws(()=>position([t('SELL','110','1','0',2)]),/초과/)});
test('수동/API 시세 선택 및 미설정 평가',()=>{const ts=[t('BUY','185','10')];assert.equal(position(ts,'200').pnl,'150');assert.equal(position(ts,'195').pnl,'100');assert.equal(position(ts).value,null);assert.equal(position(ts).rate,null)});
test('소수 수량과 원본 보존 / 유효성 검사',()=>{const p=position([t('BUY','0.1','0.2')],'0.3');assert.equal(p.cost,'0.02');assert.equal(p.pnl,'0.04');assert.throws(()=>number('-1'));assert.throws(()=>number('0',true));assert.throws(()=>number('NaN'));assert.throws(()=>number('1e8'));assert.equal(number('0.00000001',true),'0.00000001')});
